/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI/Swagger 地址提示
         * @description 用于开发期快速获取 Swagger UI 与 /v3/api-docs 地址。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example http://localhost:8080/swagger-ui/index.html */
                            swaggerUi?: string;
                            /** @example http://localhost:8080/v3/api-docs */
                            apiDocs?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Error401"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Error401"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出（撤销 refresh） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserMe"];
                    };
                };
                401: components["responses"]["Error401"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * CSV 导入用户（创建/更新）
         * @description CSV 为 UTF-8、逗号分隔，可包含表头，字段 id,name,collegeName。
         *     id 为学号/工号（账号 id，字符串）。账号唯一性为 (user_type, user_no)。
         */
        post: {
            parameters: {
                query: {
                    userType: components["schemas"]["UserType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportUsersResult"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/password:reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上级重置用户登录凭证
         * @description 由上级（管理员/导师等具备权限者）为指定用户重置登录凭证。
         *     请求体语义与登录一致：前端传入 clientSalt/clientHash。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserPasswordResetRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                404: components["responses"]["Error404"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 活动列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    term?: string;
                    status?: components["schemas"]["ActivityStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageActivity"];
                    };
                };
                401: components["responses"]["Error401"];
            };
        };
        put?: never;
        /** 创建活动（教师） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivityCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Activity"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 活动详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activityId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Activity"];
                    };
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activityId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布活动（教师） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activityId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                404: components["responses"]["Error404"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activityId}/signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 报名列表（教师） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    status?: components["schemas"]["SignupStatus"];
                };
                header?: never;
                path: {
                    activityId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageActivitySignup"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
            };
        };
        put?: never;
        /** 报名活动（学生） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activityId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivitySignup"];
                    };
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
                409: components["responses"]["Error409"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activityId}/signups/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 取消我的报名 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activityId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activityId}/signups/{signupId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审核通过（教师） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activityId: number;
                    signupId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                404: components["responses"]["Error404"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activityId}/signups/{signupId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审核拒绝（教师） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activityId: number;
                    signupId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                404: components["responses"]["Error404"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 计划列表（个人/班级） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    term?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagePlan"];
                    };
                };
                401: components["responses"]["Error401"];
            };
        };
        put?: never;
        /** 创建计划 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Plan"];
                    };
                };
                401: components["responses"]["Error401"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 计划详情（含条目） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanDetail"];
                    };
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{planId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增计划条目 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanItemCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanItem"];
                    };
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{planId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除计划条目 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
            };
        };
        options?: never;
        head?: never;
        /** 更新计划条目 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanItemUpdateRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
                422: components["responses"]["Error422"];
            };
        };
        trace?: never;
    };
    "/plan-items/{itemId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 条目进度历史 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanItemProgress"][];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                404: components["responses"]["Error404"];
            };
        };
        put?: never;
        /** 追加条目进度记录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanItemProgressCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanItemProgress"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                404: components["responses"]["Error404"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 评价列表 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    size?: components["parameters"]["Size"];
                    term?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageEvaluation"];
                    };
                };
                401: components["responses"]["Error401"];
            };
        };
        put?: never;
        /** 创建评价（教师） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvaluationCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Evaluation"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                422: components["responses"]["Error422"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 评价详情（含明细） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    evaluationId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvaluationDetail"];
                    };
                };
                401: components["responses"]["Error401"];
                404: components["responses"]["Error404"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/plan-completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 计划完成率报表 */
        get: {
            parameters: {
                query: {
                    term: string;
                    collegeId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportPlanCompletion"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                422: components["responses"]["Error422"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/activity-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 活动报名统计 */
        get: {
            parameters: {
                query: {
                    term: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportActivityStats"];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
                422: components["responses"]["Error422"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lookup/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取学生列表（用于下拉选择） */
        get: {
            parameters: {
                query?: {
                    term?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentOption"][];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lookup/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取班级列表（用于下拉选择） */
        get: {
            parameters: {
                query?: {
                    term?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClassOption"][];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lookup/colleges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取学院列表（用于下拉选择） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollegeOption"][];
                    };
                };
                401: components["responses"]["Error401"];
                403: components["responses"]["Error403"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example field 'x' is required */
            message: string;
            requestId?: string;
            details?: Record<string, never>;
        };
        StudentOption: {
            /**
             * Format: int64
             * @description 用户ID
             */
            id: number;
            /**
             * @description 学号
             * @example 2023121001
             */
            userNo: string;
            /**
             * @description 姓名
             * @example 王小明
             */
            name: string;
        };
        ClassOption: {
            /**
             * Format: int64
             * @description 班级ID
             */
            id: number;
            /**
             * @description 班级名称
             * @example 软件2301
             */
            name: string;
            /**
             * @description 所属学院名称
             * @example 信息工程学院
             */
            collegeName: string;
        };
        CollegeOption: {
            /**
             * Format: int64
             * @description 学院ID
             */
            id: number;
            /**
             * @description 学院名称
             * @example 信息工程学院
             */
            name: string;
        };
        /** @enum {string} */
        UserType: "STUDENT" | "TEACHER";
        /** @enum {string} */
        RoleCode: "ADMIN_SCHOOL" | "ADMIN_COLLEGE" | "TUTOR";
        /** @enum {string} */
        UserStatus: "ACTIVE" | "DISABLED";
        LoginRequest: {
            userType: components["schemas"]["UserType"];
            /** @example 2020123456 */
            id: string;
            /** @description 前端生成的盐（字符串） */
            clientSalt: string;
            /** @description 前端计算的哈希（字符串） */
            clientHash: string;
            /** @description 可选设备标识，用于多设备 refresh 管理 */
            deviceId?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        TokenPair: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** Format: date-time */
            refreshExpiresAt: string;
        };
        College: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        User: {
            /**
             * Format: int64
             * @description 内部 userId（数字主键）
             */
            userId: number;
            userType: components["schemas"]["UserType"];
            /** @description 账号 id（学号/工号，字符串） */
            id: string;
            name: string;
            /** Format: int64 */
            collegeId?: number | null;
            status: components["schemas"]["UserStatus"];
        };
        UserMe: components["schemas"]["User"] & {
            roles?: components["schemas"]["RoleCode"][];
        };
        ImportUsersResult: {
            created: number;
            updated: number;
            failed: number;
            failures?: components["schemas"]["ImportFailure"][];
        };
        ImportFailure: {
            /** @description 从 1 开始的 CSV 行号（含表头时仍按原始行号） */
            row: number;
            reason: string;
        };
        UserPasswordResetRequest: {
            /** @description 前端生成的盐（字符串） */
            clientSalt: string;
            /** @description 前端计算的哈希（字符串） */
            clientHash: string;
        };
        /** @enum {string} */
        ActivityStatus: "DRAFT" | "PUBLISHED" | "CLOSED";
        /** @enum {string} */
        SignupStatus: "APPLIED" | "APPROVED" | "REJECTED" | "CANCELED";
        Activity: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            classId: number;
            /** @description 班级名称 */
            className?: string;
            /** @example 2026-02-23-1 */
            term: string;
            title: string;
            description?: string | null;
            capacity?: number | null;
            requiresReview: boolean;
            status: components["schemas"]["ActivityStatus"];
            /** Format: int64 */
            createdByUserId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ActivityCreateRequest: {
            /** Format: int64 */
            classId: number;
            /** @example 2026-02-23-1 */
            term: string;
            title: string;
            description?: string;
            capacity?: number | null;
            requiresReview: boolean;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            endsAt?: string | null;
        };
        ActivitySignup: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            activityId: number;
            /** Format: int64 */
            userId: number;
            /** @description 用户学号/工号 */
            userNo?: string;
            /** @description 用户姓名 */
            userName?: string;
            status: components["schemas"]["SignupStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            reviewedAt?: string | null;
            /** Format: int64 */
            reviewedByUserId?: number | null;
        };
        /** @enum {string} */
        PlanItemStatus: "todo" | "doing" | "done";
        /** @enum {string} */
        PlanOwnerType: "CLASS" | "USER";
        Plan: {
            /** Format: int64 */
            id: number;
            ownerType: components["schemas"]["PlanOwnerType"];
            /** Format: int64 */
            ownerUserId?: number | null;
            /** Format: int64 */
            ownerClassId?: number | null;
            term: string;
            title: string;
            /** Format: date-time */
            createdAt: string;
        };
        PlanCreateRequest: {
            /** @enum {string} */
            ownerType: "USER";
            term: string;
            title: string;
        } | {
            /** @enum {string} */
            ownerType: "CLASS";
            /** Format: int64 */
            ownerClassId: number;
            term: string;
            title: string;
        };
        PlanItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            planId: number;
            title: string;
            status: components["schemas"]["PlanItemStatus"];
            sortOrder: number;
            /** Format: date */
            dueDate?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PlanItemCreateRequest: {
            title: string;
            /** Format: date */
            dueDate?: string | null;
        };
        PlanItemUpdateRequest: {
            title?: string;
            status?: components["schemas"]["PlanItemStatus"];
            sortOrder?: number;
            /** Format: date */
            dueDate?: string | null;
        };
        /** @description 实时计算的计划完成率（以 plan_item.status 为准） */
        PlanProgress: {
            /** Format: int64 */
            planId: number;
            doneCount: number;
            totalCount: number;
            /** Format: float */
            completionRate: number;
            /** Format: date-time */
            calculatedAt: string;
        };
        PlanDetail: components["schemas"]["Plan"] & {
            items: components["schemas"]["PlanItem"][];
            progress?: components["schemas"]["PlanProgress"];
        };
        /** @description 条目进度历史记录（append-only） */
        PlanItemProgress: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            planItemId: number;
            percent: number;
            note?: string | null;
            /** Format: int64 */
            createdByUserId: number;
            /** Format: date-time */
            createdAt: string;
        };
        PlanItemProgressCreateRequest: {
            percent: number;
            note?: string | null;
        };
        Evaluation: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            evaluatorUserId: number;
            /** @description 评价人学号/工号 */
            evaluatorUserNo?: string;
            /** @description 评价人姓名 */
            evaluatorUserName?: string;
            /** Format: int64 */
            evaluateeUserId: number;
            /** @description 被评价人学号/工号 */
            evaluateeUserNo?: string;
            /** @description 被评价人姓名 */
            evaluateeUserName?: string;
            term: string;
            scoreTotal: number;
            comment?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvaluationCreateRequest: {
            /** Format: int64 */
            evaluateeUserId: number;
            term: string;
            scoreTotal: number;
            comment?: string;
            details?: components["schemas"]["EvaluationDetailItem"][];
        };
        EvaluationDetailItem: {
            /** @example attitude */
            itemKey: string;
            score: number;
            comment?: string;
        };
        EvaluationDetail: components["schemas"]["Evaluation"] & {
            details: components["schemas"]["EvaluationDetailItem"][];
        };
        ReportPlanCompletion: {
            term: string;
            items: {
                /** @description 统计范围描述（如“学院:xx”或“班级:xx”） */
                scope: string;
                doneCount: number;
                totalCount: number;
                /** Format: float */
                completionRate: number;
            }[];
        };
        ReportActivityStats: {
            term: string;
            items: {
                /** Format: int64 */
                activityId: number;
                title: string;
                appliedCount: number;
                approvedCount: number;
            }[];
        };
        PageActivity: {
            page: number;
            size: number;
            total: number;
            items: components["schemas"]["Activity"][];
        };
        PageActivitySignup: {
            page: number;
            size: number;
            total: number;
            items: components["schemas"]["ActivitySignup"][];
        };
        PagePlan: {
            page: number;
            size: number;
            total: number;
            items: components["schemas"]["Plan"][];
        };
        PageEvaluation: {
            page: number;
            size: number;
            total: number;
            items: components["schemas"]["Evaluation"][];
        };
    };
    responses: {
        /** @description Unauthorized */
        Error401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden */
        Error403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Error409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unprocessable Entity */
        Error422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
